name: Generate Snake Game from GitHub Contributions

on:
  schedule:
    - cron: '0 0 * * *'  # 每天生成一次
  push:
    branches:
      - main  # 或你主要贡献的分支

jobs:
  generate-snake:
    runs-on: ubuntu-latest

    steps:
      # 使用 Platane 的 snk action 生成贪吃蛇动画
      - name: Generate Snake Game from Contribution Graph
        uses: Platane/snk@v2
        with:
          github_user_name: nisikin  
          output: dist/snake.svg  

      # 将生成的文件上传到 GitHub Pages 或保存为 artifact
      - name: Upload Snake Game Animation
        uses: actions/upload-artifact@v2
        with:
          name: snake-game-animation
          path: dist/snake.svg  # 指定生成的文件路径